server:
    port: 9297

spring:
  application:
    name: config-service
    cloud:
        config:
            server:
            git:
                uri:https://config.url
            clone-on-start: true