spring.security.oauth2:
  client:
    registration:
      user-accounts-app-oidc:
        provider: spring
        client-id: "user-accounts-app"
        client-secret: secret
        authorization-grant-type: "authorization_code"
        redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
        scope: openid, profile, accounts.read
        client-name: user-accounts-app-oidc
    provider:
      spring:
        issuer-uri: http://localhost:9000
    resourceserver:
      jwt:
        jwk-set-uri: http://localhost:9000/oauth2/jwks


oauth2:
  authorizationserver:
    client:
      user-accounts-app:
        client-id: user-accounts-app
        client-secret: secret
        authorized-grant-types:
          - "authorization_code"
          - "refresh_token"
          - "client_credentials"

