server:
    port: 9297

spring:
  application:
      name: config-service

  cloud:
      config:
        server:
          git:
            uri: https://github.com/calmHeaven/config-server.git
            clone-on-start: true
  main:
    web-application-type: reactive
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.cloud.config: DEBUG
debug: true